language: python
python:
    - "2.7"
    - "3.6"
    - "pypy"

before_install:
    - pip install pycodestyle
    - pycodestyle $TRAVIS_BUILD_DIR/samples/*.py
    - pycodestyle $TRAVIS_BUILD_DIR/samples/tools/*.py

install:
    - python setup.py bdist_egg
    - pip install -e file://$TRAVIS_BUILD_DIR

script:
    nosetests


